
name: build-workflow

on:
  workflow_run:
    workflows: ["commit-workflow"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build_amd64:

    name: Build tedge and mapper Debian packages for amd64
    runs-on: Ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: Checkout
        run: echo "NOP"

      - name: enable toolchain via github action
        run: echo "NOP"

      - name: Enable cache
        run: echo "NOP"

      - name: Install cargo-deb
        run: echo "NOP"

      - name: Build tedge debian package
        run: echo "NOP"

      - name: Build tedge_mapper debian package
        run: echo "NOP"

      - name: build examples for amd64
        run: echo "NOP"

      - name: Upload artifacts as zip
        run: echo "NOP"

      - name: upload amd64 examples as zip
        run: echo "NOP"

  build_armv7:

    name: Build tedge and mapper Debian for armv7
    runs-on: Ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      TARGET: armv7-unknown-linux-gnueabihf

    steps:

      - name: checkout
        run: echo "NOP"

      - name: enable toolchain via github action
        run: echo "NOP"

      - name: Enable cache
        run: echo "NOP"

      - name: install cargo-deb
        run: echo "NOP"

      - name: install cargo-strip
        run: echo "NOP"

      - name: build cross release for target
        run: echo "NOP"

      - name: strip binaries (cargo deb fails to strip)
        run: echo "NOP"

      - name: build tedge debian package for target
        run: echo "NOP"

      - name: build tedge_mapper debian package for target
        run: echo "NOP"

      - name: build examples
        run: echo "NOP"

      - name: upload debian packages as zip
        run: echo "NOP"

      - name: upload examples as zip
        run: echo "NOP"

