name: commit-workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  cargo-fmt:

    name: Run cargo fmt
    runs-on: Ubuntu-20.04

    steps:

      - name: Checkout
        run: echo "NOP"

      - name: Cargo fmt
        run: echo "NOP"


  cargo-clippy:

    name: Run cargo clippy
    runs-on: Ubuntu-20.04

    steps:

      - name: Checkout
        run: echo "NOP"

      - name: Enable cache
        run: echo "NOP"

      - name: Cargo clippy
        run: echo "NOP"

  cargo-test:

    name: Run cargo test
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:

      - name: Checkout
        run: echo "NOP"

      - name: Enable cache
        run: echo "NOP"

      - name: Cargo test
        run: echo "NOP"

  cargo-build:

    name: Run cargo build
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:

      - name: Checkout
        run: echo "NOP"

      - name: Enable cache
        run: echo "NOP"

      - name: Cargo build
        run: echo "NOP"

  cargo-tarpaulin:

    name: Run cargo tarpaulin
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:

      - name: Checkout
        run: echo "NOP"

      - name: Enable cache
        run: echo "NOP"

      - name: install libssl
        run: echo "NOP"

      - name: Cargo install tarpaulin
        run: echo "NOP"

      - name: Cargo tarpaulin
        run: echo "NOP"

      - name: Upload to codecov.io
        run: echo "NOP"

  cargo-audit:

    name: Run cargo audit
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]


    steps:

      - name: Checkout
        run: echo "NOP"

      - name: Cargo audit
        run: echo "NOP"

  cargo-outdated:

    name: Run cargo outdated
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:

      - name: Checkout
        run: echo "NOP"

      - name: Cargo outdated
        run: echo "NOP"
