name: integration-test-workflow

on:
  workflow_dispatch:
    branches: [ main ]
  workflow_run:
    workflows: ["build-workflow"]
    branches: [main]
    types:
      - completed
env:
  CARGO_TERM_COLOR: always

jobs:

  install-and-use-amd64:

    runs-on: Ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
        - name: checkout
          run: echo "NOP"

        - name: Download artifact
          run: echo "NOP"

        - name: purge
          run: echo "NOP"

        - name: install mosquitto
          run: echo "NOP"

        - name: install packages
          run: echo "NOP"

        - name: run tedge help
          run: echo "NOP"

  cargo-test-features:

    name: Run cargo test features
    runs-on: Ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: Checkout
        run: echo "NOP"

      - name: Enable cache
        run: echo "NOP"

      - name: Cargo test features (compile)
        run: echo "NOP"

        # To run the test for features here is kind of experimental
        # they could fail if GitHub blocks external connections.
        # It seems like they rarely do.
      - name: Cargo test features
        run: echo "NOP"

  install-and-use-rpi:

    runs-on: [self-hosted, Linux, ARM]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
        - name: checkout
          run: echo "NOP"

        - name: Download artifact
          run: echo "NOP"

        - name: purge
          run: echo "NOP"

        - name: install mosquitto
          run: echo "NOP"

        - name: install packages
          run: echo "NOP"

        - name: run tedge help
          run: echo "NOP"

        - name: Download artifact
          run: echo "NOP"

        - name: Run Smoke Test
          run: echo "NOP"
