name: system-test-workflow

on:

  workflow_dispatch:
    branches: [ main ]
  workflow_run:
    workflows: ["integration-test-workflow"]
    branches: [main]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  system-test:
    runs-on: [self-hosted, Linux, ARM]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    - name: checkout
        run: echo "NOP"

    - name: Run all Tests
        run: echo "NOP"

    - name: upload results as zip
        run: echo "NOP"
